version: '3.7'
services:
    postgres:
        image: postgres:13.1
        restart: always
        environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
        ports:
          - '5438:5432'
        volumes: 
          - ./resources/scripts:/docker-entrypoint-initdb.d